// AUTO-GENERATED by scripts/gen-domain-map.mjs — do not edit by hand.
export default {
  "algierispizza.com": "algieris",
  "bigjimsnewmilford.com": "bigjims",
  "broadwaypizzawestwood.com": "broadway",
  "frankspizzapomptonlakes.com": "frankspompton",
  "gabyspizzaandgrill.com": "gabys",
  "getfranks.com": "franksoakland",
  "ginosbellevillenj.com": "ginos",
  "mamarosapasta.com": "mamarosa",
  "marcsdeliandpizza.com": "marcs",
  "newparktavern.com": "newparktavern",
  "parkpizza.co": "parkpizza",
  "ralphseastrutherford.com": "ralphs",
  "testpizza.co": "test",
  "theoriginalangelospizzeria.com": "angelos",
  "torinomenu.com": "torino",
}
