-- ============================================================================
-- Migration 036: Uber Direct webhook signing key — generated by DirectBite,
--                registered in Uber's dashboard
-- ============================================================================
--
-- Milestone M9b.1 of the Uber Direct integration. Discovered during M9b
-- deployment: Uber's developer dashboard requires the merchant to provide
-- a separate webhook signing key when registering a webhook URL. This is
-- distinct from the OAuth client_secret (which authenticates DirectBite's
-- API calls TO Uber); the webhook signing key is what Uber uses to sign
-- the event payloads it sends BACK to us, so we can verify their
-- authenticity via HMAC-SHA256.
--
-- Adds:
--   restaurants.uber_webhook_signing_secret text — HMAC-SHA256 key used
--   by Uber to sign webhook event bodies. Each restaurant generates their
--   own key during onboarding (~32 bytes random hex) and pastes the same
--   value into BOTH:
--     1. DirectBite's restaurants row (this column)
--     2. The restaurant's Uber Direct merchant dashboard webhook config
--
--   M9b's uber-webhook function reads this column to verify each incoming
--   event's HMAC signature.
--
-- Why a separate column (not reusing uber_client_secret):
--   - uber_client_secret authenticates DirectBite's OAuth flow when
--     minting access tokens for delivery_quotes / deliveries API calls.
--     It is provided BY Uber.
--   - uber_webhook_signing_secret signs the webhook payloads Uber sends
--     TO us. It is provided BY the merchant (us) and registered in Uber's
--     dashboard.
--   - These are different credentials with different rotation cadences
--     and different blast radii on compromise.
--
-- Nullable for backward compatibility:
--   - Pre-M9b.1 restaurants will have NULL; uber-webhook falls back to
--     uber_client_secret as the HMAC key for transitional state.
--   - Once all uber_direct restaurants have populated this column, the
--     fallback path in uber-webhook can be removed (M9b.2 cleanup).
--
-- Zero impact on existing 8 production restaurants:
--   - All in_house — no Uber webhooks ever reach the handler for them.
--   - Column stays NULL.
--
-- Idempotency: ADD COLUMN uses IF NOT EXISTS. Wrapped in BEGIN/COMMIT.
--
-- Rollback: see reverse SQL block at the bottom of this file.
-- ============================================================================

BEGIN;

ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS uber_webhook_signing_secret text;

COMMIT;

-- ============================================================================
-- REVERSE SQL (rollback) — DO NOT RUN unless undoing this migration.
-- Wrapped in BEGIN/COMMIT; uncomment and run as a single block in SQL
-- Editor.
-- ============================================================================
--
-- BEGIN;
--
-- ALTER TABLE restaurants DROP COLUMN IF EXISTS uber_webhook_signing_secret;
--
-- COMMIT;
